### See https://github.com/bbatsov/rubocop/tree/master/manual for details
AllCops:
  Include:
  - "**/*.gemspec"
  - "**/*.podspec"
  - "**/*.jbuilder"
  - "**/*.rake"
  - "**/*.opal"
  - "**/Gemfile"
  - "**/Rakefile"
  - "**/Capfile"
  - "**/Guardfile"
  - "**/Podfile"
  - "**/Thorfile"
  - "**/Vagrantfile"
  - "**/Berksfile"
  - "**/Cheffile"
  - "**/Vagabondfile"
  Exclude:
  - "vendor/**/*"
  - "**/schema.rb"
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find: detect
    find_all: select
    reduce: inject
Style/CommentAnnotation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Style/Encoding:
  Description: Use UTF-8 as the source file encoding.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#utf-8
  Enabled: false
Style/For:
  Enabled: true
Style/FormatString:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Naming/PredicateName:
  NamePrefixBlacklist:
  - is_
Style/RaiseArgs:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SymbolProc:
  IgnoredMethods:
  - respond_to
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
  ExactNameMatch: false
  AllowPredicates: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
  WordRegex: !ruby/regexp /\A[\p{Word}]+\z/
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
  Max: 40
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/Alias:
  Enabled: false
Style/ArrayJoin:
 Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/Proc:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength: # don't care about block length for specs
  Exclude:
    - "spec/**/*.rb"
